title:              "What I Project"
tagline:            "다재다능 마케터 내가 해볼라고."
email:              "k.j.lee7154@gmail.com"
description:        "요즘 마케터는 개발도 하고, 디자인도 하고 그런다면서? 그거 해보려고. 까짓거 다재다능 마케터 해보지 뭐. 같이 할래? “내”가 해보는 마케터, What “I” Project."
author:             "Kyungji Lee"
baseurl:            "/"
url:                "https://whatiproject.com"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"

# Social Profiles
twitter_username:
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
# 블로그 disqus shortname
disqus:
  shortname: whatiproject
